/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Card {
  'id' : bigint,
  'title' : string,
  'description' : [] | [string],
  'projectId' : bigint,
  'assignedUserId' : [] | [bigint],
  'columnId' : bigint,
}
export interface ColumnView {
  'id' : bigint,
  'name' : string,
  'projectId' : bigint,
  'cardIds' : Array<bigint>,
}
export interface Project { 'id' : bigint, 'name' : string }
export interface Revision {
  'id' : bigint,
  'actorName' : string,
  'description' : string,
  'projectId' : bigint,
  'timestamp' : bigint,
  'cardId' : [] | [bigint],
  'revisionType' : string,
}
export interface User { 'id' : bigint, 'name' : string, 'pinHash' : string }
export interface _SERVICE {
  'assignCard' : ActorMethod<[bigint, [] | [bigint], bigint], undefined>,
  'changeUserPin' : ActorMethod<[bigint, string, string], undefined>,
  'clearRevisions' : ActorMethod<[], undefined>,
  'createCard' : ActorMethod<
    [string, [] | [string], bigint, bigint, bigint],
    bigint
  >,
  'createColumn' : ActorMethod<[string, bigint, bigint], bigint>,
  'createProject' : ActorMethod<[string, bigint], bigint>,
  'createUser' : ActorMethod<[string, string], bigint>,
  'deleteCard' : ActorMethod<[bigint, bigint], undefined>,
  'deleteColumn' : ActorMethod<[bigint, bigint], undefined>,
  'deleteProject' : ActorMethod<[bigint, bigint], undefined>,
  'deleteUser' : ActorMethod<[bigint], undefined>,
  'getCardRevisions' : ActorMethod<[bigint], Array<Revision>>,
  'getCards' : ActorMethod<[bigint], Array<Card>>,
  'getColumns' : ActorMethod<[bigint], Array<ColumnView>>,
  'getProjects' : ActorMethod<[], Array<Project>>,
  'getRevisions' : ActorMethod<[bigint], Array<Revision>>,
  'getUsers' : ActorMethod<[], Array<User>>,
  'initBoard' : ActorMethod<[], undefined>,
  'initDefaultProject' : ActorMethod<[], bigint>,
  'moveCard' : ActorMethod<[bigint, bigint, bigint, bigint], undefined>,
  'renameColumn' : ActorMethod<[bigint, string, bigint], undefined>,
  'renameProject' : ActorMethod<[bigint, string, bigint], undefined>,
  'reorderColumns' : ActorMethod<[Array<bigint>, bigint], undefined>,
  'resetUserPin' : ActorMethod<[bigint, string, string], undefined>,
  'setAdminPin' : ActorMethod<[string], undefined>,
  'updateCard' : ActorMethod<
    [bigint, string, [] | [string], bigint],
    undefined
  >,
  'verifyPin' : ActorMethod<[bigint, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];