/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Swimlane {
    id: bigint;
    order: bigint;
    name: string;
    projectId: bigint;
}
export interface ColumnView {
    id: bigint;
    name: string;
    projectId: bigint;
    cardIds: Array<bigint>;
}
export interface Tag {
    id: bigint;
    name: string;
    color: string;
    projectId: bigint;
}
export interface Comment {
    id: bigint;
    authorId: bigint;
    text: string;
    authorName: string;
    timestamp: bigint;
    cardId: bigint;
}
export interface Card {
    id: bigint;
    title: string;
    createdAt: bigint;
    tags: Array<bigint>;
    dueDate?: bigint;
    description?: string;
    isArchived: boolean;
    projectId: bigint;
    assignedUserId?: bigint;
    swimlaneId?: bigint;
    columnId: bigint;
    archivedAt?: bigint;
}
export interface User {
    id: bigint;
    isMasterAdmin: boolean;
    name: string;
    securityQuestion?: string;
    pinHash: string;
    isAdmin: boolean;
    securityAnswerHash?: string;
}
export interface ChecklistItem {
    id: bigint;
    order: bigint;
    createdAt: bigint;
    text: string;
    isDone: boolean;
    cardId: bigint;
}
export interface Project {
    id: bigint;
    name: string;
    swimlanesEnabled: boolean;
}
export interface FilterPreset {
    id: bigint;
    dateTo: string;
    assigneeId?: bigint;
    createdByUserId: bigint;
    name: string;
    tagIds: Array<bigint>;
    projectId: bigint;
    textSearch: string;
    unassignedOnly: boolean;
    dateFrom: string;
    dateField?: string;
}
export interface Revision {
    id: bigint;
    actorName: string;
    description: string;
    projectId: bigint;
    timestamp: bigint;
    cardId?: bigint;
    revisionType: string;
}
export interface ProjectSummary {
    unassignedCount: bigint;
    totalCards: bigint;
    overdueCount: bigint;
    dueSoonCount: bigint;
    tagCounts: Array<[bigint, bigint]>;
}
export interface backendInterface {
    addChecklistItem(cardId: bigint, text: string, actorUserId: bigint): Promise<bigint>;
    addComment(cardId: bigint, text: string, actorUserId: bigint): Promise<bigint>;
    archiveCard(cardId: bigint, actorUserId: bigint): Promise<void>;
    assignCard(cardId: bigint, userId: bigint | null, actorUserId: bigint): Promise<void>;
    changeUserPin(userId: bigint, oldPinHash: string, newPinHash: string): Promise<void>;
    clearRevisions(): Promise<void>;
    createCard(title: string, description: string | null, columnId: bigint, actorUserId: bigint, projectId: bigint): Promise<bigint>;
    createColumn(name: string, actorUserId: bigint, projectId: bigint): Promise<bigint>;
    createProject(name: string, actorUserId: bigint): Promise<bigint>;
    createSwimlane(projectId: bigint, name: string, actorUserId: bigint): Promise<bigint>;
    createTag(projectId: bigint, name: string, color: string, actorUserId: bigint): Promise<bigint>;
    createUser(name: string, pinHash: string): Promise<bigint>;
    deleteCard(cardId: bigint, actorUserId: bigint): Promise<void>;
    deleteChecklistItem(itemId: bigint, actorUserId: bigint): Promise<void>;
    deleteColumn(columnId: bigint, actorUserId: bigint): Promise<void>;
    deleteComment(commentId: bigint, actorUserId: bigint): Promise<void>;
    deleteFilterPreset(presetId: bigint, actorUserId: bigint): Promise<void>;
    deleteProject(projectId: bigint, actorUserId: bigint): Promise<void>;
    deleteSwimlane(swimlaneId: bigint, actorUserId: bigint): Promise<void>;
    deleteTag(tagId: bigint, actorUserId: bigint): Promise<void>;
    deleteUser(userId: bigint, actorUserId: bigint): Promise<void>;
    demoteUser(userId: bigint, actorUserId: bigint): Promise<void>;
    disableSwimlanes(projectId: bigint, actorUserId: bigint): Promise<void>;
    enableSwimlanes(projectId: bigint, actorUserId: bigint): Promise<void>;
    getArchivedCards(projectId: bigint): Promise<Array<Card>>;
    getCardComments(cardId: bigint): Promise<Array<Comment>>;
    getCardRevisions(cardId: bigint): Promise<Array<Revision>>;
    getCards(projectId: bigint): Promise<Array<Card>>;
    getChecklistItems(cardId: bigint): Promise<Array<ChecklistItem>>;
    getColumns(projectId: bigint): Promise<Array<ColumnView>>;
    getFilterPresets(projectId: bigint): Promise<Array<FilterPreset>>;
    getProjectSummary(projectId: bigint): Promise<ProjectSummary>;
    getProjectTags(projectId: bigint): Promise<Array<Tag>>;
    getProjects(): Promise<Array<Project>>;
    getRevisions(projectId: bigint): Promise<Array<Revision>>;
    getSwimlanes(projectId: bigint): Promise<Array<Swimlane>>;
    getUsers(): Promise<Array<User>>;
    initBoard(): Promise<void>;
    initDefaultProject(): Promise<bigint>;
    isAdminSetup(): Promise<boolean>;
    moveCard(cardId: bigint, targetColumnId: bigint, newPosition: bigint, actorUserId: bigint): Promise<void>;
    moveCards(cardIds: Array<bigint>, targetColumnId: bigint, actorUserId: bigint): Promise<void>;
    promoteUser(userId: bigint, actorUserId: bigint): Promise<void>;
    renameColumn(columnId: bigint, newName: string, actorUserId: bigint): Promise<void>;
    renameProject(projectId: bigint, newName: string, actorUserId: bigint): Promise<void>;
    renameSwimlane(swimlaneId: bigint, newName: string, actorUserId: bigint): Promise<void>;
    renameTag(tagId: bigint, newName: string, actorUserId: bigint): Promise<void>;
    renameUser(userId: bigint, newName: string, actorUserId: bigint): Promise<void>;
    reorderChecklistItems(cardId: bigint, newOrder: Array<bigint>, actorUserId: bigint): Promise<void>;
    reorderColumns(newOrder: Array<bigint>, actorUserId: bigint): Promise<void>;
    reorderSwimlanes(newOrder: Array<bigint>, actorUserId: bigint): Promise<void>;
    resetMasterAdminPinWithSecurityAnswer(answerHash: string, newPinHash: string): Promise<boolean>;
    resetUserPin(userId: bigint, actorUserId: bigint, newPinHash: string): Promise<void>;
    restoreCard(cardId: bigint, actorUserId: bigint): Promise<void>;
    saveFilterPreset(projectId: bigint, createdByUserId: bigint, name: string, assigneeId: bigint | null, tagIds: Array<bigint>, unassignedOnly: boolean, textSearch: string, dateField: string | null, dateFrom: string, dateTo: string): Promise<bigint>;
    setMasterAdminSecurityQuestion(question: string, answerHash: string, actorUserId: bigint): Promise<void>;
    setupMasterAdmin(name: string, pinHash: string): Promise<bigint>;
    updateCard(cardId: bigint, title: string, description: string | null, actorUserId: bigint): Promise<void>;
    updateCardDueDate(cardId: bigint, dueDate: bigint | null, actorUserId: bigint): Promise<void>;
    updateCardSwimlane(cardId: bigint, swimlaneId: bigint | null, actorUserId: bigint): Promise<void>;
    updateCardTags(cardId: bigint, tagIds: Array<bigint>, actorUserId: bigint): Promise<void>;
    updateChecklistItem(itemId: bigint, text: string, isDone: boolean, actorUserId: bigint): Promise<void>;
    verifyPin(userId: bigint, pinHash: string): Promise<boolean>;
}
import type { Card as _Card, FilterPreset as _FilterPreset, Revision as _Revision, User as _User } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addChecklistItem(arg0: bigint, arg1: string, arg2: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addChecklistItem(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addChecklistItem(arg0, arg1, arg2);
            return result;
        }
    }
    async addComment(arg0: bigint, arg1: string, arg2: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addComment(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addComment(arg0, arg1, arg2);
            return result;
        }
    }
    async archiveCard(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.archiveCard(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.archiveCard(arg0, arg1);
            return result;
        }
    }
    async assignCard(arg0: bigint, arg1: bigint | null, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCard(arg0, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCard(arg0, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async changeUserPin(arg0: bigint, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.changeUserPin(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.changeUserPin(arg0, arg1, arg2);
            return result;
        }
    }
    async clearRevisions(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearRevisions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearRevisions();
            return result;
        }
    }
    async createCard(arg0: string, arg1: string | null, arg2: bigint, arg3: bigint, arg4: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createCard(arg0, to_candid_opt_n2(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCard(arg0, to_candid_opt_n2(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4);
            return result;
        }
    }
    async createColumn(arg0: string, arg1: bigint, arg2: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createColumn(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createColumn(arg0, arg1, arg2);
            return result;
        }
    }
    async createProject(arg0: string, arg1: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createProject(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProject(arg0, arg1);
            return result;
        }
    }
    async createSwimlane(arg0: bigint, arg1: string, arg2: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createSwimlane(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSwimlane(arg0, arg1, arg2);
            return result;
        }
    }
    async createTag(arg0: bigint, arg1: string, arg2: string, arg3: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createTag(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTag(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async createUser(arg0: string, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createUser(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createUser(arg0, arg1);
            return result;
        }
    }
    async deleteCard(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCard(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCard(arg0, arg1);
            return result;
        }
    }
    async deleteChecklistItem(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteChecklistItem(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteChecklistItem(arg0, arg1);
            return result;
        }
    }
    async deleteColumn(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteColumn(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteColumn(arg0, arg1);
            return result;
        }
    }
    async deleteComment(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteComment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteComment(arg0, arg1);
            return result;
        }
    }
    async deleteFilterPreset(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFilterPreset(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFilterPreset(arg0, arg1);
            return result;
        }
    }
    async deleteProject(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProject(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProject(arg0, arg1);
            return result;
        }
    }
    async deleteSwimlane(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSwimlane(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSwimlane(arg0, arg1);
            return result;
        }
    }
    async deleteTag(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTag(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTag(arg0, arg1);
            return result;
        }
    }
    async deleteUser(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteUser(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteUser(arg0, arg1);
            return result;
        }
    }
    async demoteUser(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.demoteUser(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.demoteUser(arg0, arg1);
            return result;
        }
    }
    async disableSwimlanes(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.disableSwimlanes(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.disableSwimlanes(arg0, arg1);
            return result;
        }
    }
    async enableSwimlanes(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.enableSwimlanes(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.enableSwimlanes(arg0, arg1);
            return result;
        }
    }
    async getArchivedCards(arg0: bigint): Promise<Array<Card>> {
        if (this.processError) {
            try {
                const result = await this.actor.getArchivedCards(arg0);
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getArchivedCards(arg0);
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCardComments(arg0: bigint): Promise<Array<Comment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCardComments(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCardComments(arg0);
            return result;
        }
    }
    async getCardRevisions(arg0: bigint): Promise<Array<Revision>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCardRevisions(arg0);
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCardRevisions(arg0);
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCards(arg0: bigint): Promise<Array<Card>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCards(arg0);
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCards(arg0);
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChecklistItems(arg0: bigint): Promise<Array<ChecklistItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChecklistItems(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChecklistItems(arg0);
            return result;
        }
    }
    async getColumns(arg0: bigint): Promise<Array<ColumnView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getColumns(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getColumns(arg0);
            return result;
        }
    }
    async getFilterPresets(arg0: bigint): Promise<Array<FilterPreset>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFilterPresets(arg0);
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFilterPresets(arg0);
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProjectSummary(arg0: bigint): Promise<ProjectSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getProjectSummary(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProjectSummary(arg0);
            return result;
        }
    }
    async getProjectTags(arg0: bigint): Promise<Array<Tag>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProjectTags(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProjectTags(arg0);
            return result;
        }
    }
    async getProjects(): Promise<Array<Project>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProjects();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProjects();
            return result;
        }
    }
    async getRevisions(arg0: bigint): Promise<Array<Revision>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRevisions(arg0);
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRevisions(arg0);
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSwimlanes(arg0: bigint): Promise<Array<Swimlane>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSwimlanes(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSwimlanes(arg0);
            return result;
        }
    }
    async getUsers(): Promise<Array<User>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUsers();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUsers();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async initBoard(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initBoard();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initBoard();
            return result;
        }
    }
    async initDefaultProject(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.initDefaultProject();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initDefaultProject();
            return result;
        }
    }
    async isAdminSetup(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAdminSetup();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAdminSetup();
            return result;
        }
    }
    async moveCard(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.moveCard(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.moveCard(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async moveCards(arg0: Array<bigint>, arg1: bigint, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.moveCards(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.moveCards(arg0, arg1, arg2);
            return result;
        }
    }
    async promoteUser(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.promoteUser(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.promoteUser(arg0, arg1);
            return result;
        }
    }
    async renameColumn(arg0: bigint, arg1: string, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.renameColumn(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.renameColumn(arg0, arg1, arg2);
            return result;
        }
    }
    async renameProject(arg0: bigint, arg1: string, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.renameProject(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.renameProject(arg0, arg1, arg2);
            return result;
        }
    }
    async renameSwimlane(arg0: bigint, arg1: string, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.renameSwimlane(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.renameSwimlane(arg0, arg1, arg2);
            return result;
        }
    }
    async renameTag(arg0: bigint, arg1: string, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.renameTag(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.renameTag(arg0, arg1, arg2);
            return result;
        }
    }
    async renameUser(arg0: bigint, arg1: string, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.renameUser(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.renameUser(arg0, arg1, arg2);
            return result;
        }
    }
    async reorderChecklistItems(arg0: bigint, arg1: Array<bigint>, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.reorderChecklistItems(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reorderChecklistItems(arg0, arg1, arg2);
            return result;
        }
    }
    async reorderColumns(arg0: Array<bigint>, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.reorderColumns(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reorderColumns(arg0, arg1);
            return result;
        }
    }
    async reorderSwimlanes(arg0: Array<bigint>, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.reorderSwimlanes(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reorderSwimlanes(arg0, arg1);
            return result;
        }
    }
    async resetMasterAdminPinWithSecurityAnswer(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.resetMasterAdminPinWithSecurityAnswer(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetMasterAdminPinWithSecurityAnswer(arg0, arg1);
            return result;
        }
    }
    async resetUserPin(arg0: bigint, arg1: bigint, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resetUserPin(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetUserPin(arg0, arg1, arg2);
            return result;
        }
    }
    async restoreCard(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.restoreCard(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.restoreCard(arg0, arg1);
            return result;
        }
    }
    async saveFilterPreset(arg0: bigint, arg1: bigint, arg2: string, arg3: bigint | null, arg4: Array<bigint>, arg5: boolean, arg6: string, arg7: string | null, arg8: string, arg9: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.saveFilterPreset(arg0, arg1, arg2, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6, to_candid_opt_n2(this._uploadFile, this._downloadFile, arg7), arg8, arg9);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveFilterPreset(arg0, arg1, arg2, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6, to_candid_opt_n2(this._uploadFile, this._downloadFile, arg7), arg8, arg9);
            return result;
        }
    }
    async setMasterAdminSecurityQuestion(arg0: string, arg1: string, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setMasterAdminSecurityQuestion(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setMasterAdminSecurityQuestion(arg0, arg1, arg2);
            return result;
        }
    }
    async setupMasterAdmin(arg0: string, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.setupMasterAdmin(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setupMasterAdmin(arg0, arg1);
            return result;
        }
    }
    async updateCard(arg0: bigint, arg1: string, arg2: string | null, arg3: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCard(arg0, arg1, to_candid_opt_n2(this._uploadFile, this._downloadFile, arg2), arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCard(arg0, arg1, to_candid_opt_n2(this._uploadFile, this._downloadFile, arg2), arg3);
            return result;
        }
    }
    async updateCardDueDate(arg0: bigint, arg1: bigint | null, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCardDueDate(arg0, to_candid_opt_n18(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCardDueDate(arg0, to_candid_opt_n18(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async updateCardSwimlane(arg0: bigint, arg1: bigint | null, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCardSwimlane(arg0, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCardSwimlane(arg0, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async updateCardTags(arg0: bigint, arg1: Array<bigint>, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCardTags(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCardTags(arg0, arg1, arg2);
            return result;
        }
    }
    async updateChecklistItem(arg0: bigint, arg1: string, arg2: boolean, arg3: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateChecklistItem(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateChecklistItem(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async verifyPin(arg0: bigint, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyPin(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyPin(arg0, arg1);
            return result;
        }
    }
}
function from_candid_Card_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Card): Card {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_FilterPreset_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FilterPreset): FilterPreset {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_Revision_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Revision): Revision {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_User_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _User): User {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    actorName: string;
    description: string;
    projectId: bigint;
    timestamp: bigint;
    cardId: [] | [bigint];
    revisionType: string;
}): {
    id: bigint;
    actorName: string;
    description: string;
    projectId: bigint;
    timestamp: bigint;
    cardId?: bigint;
    revisionType: string;
} {
    return {
        id: value.id,
        actorName: value.actorName,
        description: value.description,
        projectId: value.projectId,
        timestamp: value.timestamp,
        cardId: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.cardId)),
        revisionType: value.revisionType
    };
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    dateTo: string;
    assigneeId: [] | [bigint];
    createdByUserId: bigint;
    name: string;
    tagIds: Array<bigint>;
    projectId: bigint;
    textSearch: string;
    unassignedOnly: boolean;
    dateFrom: string;
    dateField: [] | [string];
}): {
    id: bigint;
    dateTo: string;
    assigneeId?: bigint;
    createdByUserId: bigint;
    name: string;
    tagIds: Array<bigint>;
    projectId: bigint;
    textSearch: string;
    unassignedOnly: boolean;
    dateFrom: string;
    dateField?: string;
} {
    return {
        id: value.id,
        dateTo: value.dateTo,
        assigneeId: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.assigneeId)),
        createdByUserId: value.createdByUserId,
        name: value.name,
        tagIds: value.tagIds,
        projectId: value.projectId,
        textSearch: value.textSearch,
        unassignedOnly: value.unassignedOnly,
        dateFrom: value.dateFrom,
        dateField: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.dateField))
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    isMasterAdmin: boolean;
    name: string;
    securityQuestion: [] | [string];
    pinHash: string;
    isAdmin: boolean;
    securityAnswerHash: [] | [string];
}): {
    id: bigint;
    isMasterAdmin: boolean;
    name: string;
    securityQuestion?: string;
    pinHash: string;
    isAdmin: boolean;
    securityAnswerHash?: string;
} {
    return {
        id: value.id,
        isMasterAdmin: value.isMasterAdmin,
        name: value.name,
        securityQuestion: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.securityQuestion)),
        pinHash: value.pinHash,
        isAdmin: value.isAdmin,
        securityAnswerHash: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.securityAnswerHash))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    createdAt: bigint;
    tags: Array<bigint>;
    dueDate: [] | [bigint];
    description: [] | [string];
    isArchived: boolean;
    projectId: bigint;
    assignedUserId: [] | [bigint];
    swimlaneId: [] | [bigint];
    columnId: bigint;
    archivedAt: [] | [bigint];
}): {
    id: bigint;
    title: string;
    createdAt: bigint;
    tags: Array<bigint>;
    dueDate?: bigint;
    description?: string;
    isArchived: boolean;
    projectId: bigint;
    assignedUserId?: bigint;
    swimlaneId?: bigint;
    columnId: bigint;
    archivedAt?: bigint;
} {
    return {
        id: value.id,
        title: value.title,
        createdAt: value.createdAt,
        tags: value.tags,
        dueDate: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.dueDate)),
        description: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.description)),
        isArchived: value.isArchived,
        projectId: value.projectId,
        assignedUserId: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.assignedUserId)),
        swimlaneId: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.swimlaneId)),
        columnId: value.columnId,
        archivedAt: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.archivedAt))
    };
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FilterPreset>): Array<FilterPreset> {
    return value.map((x)=>from_candid_FilterPreset_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_User>): Array<User> {
    return value.map((x)=>from_candid_User_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Card>): Array<Card> {
    return value.map((x)=>from_candid_Card_n4(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Revision>): Array<Revision> {
    return value.map((x)=>from_candid_Revision_n10(_uploadFile, _downloadFile, x));
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
